name: Check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check-client:
    name: Check Client
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install --frozen-lockfile

      - run: bun check
        working-directory: ./client

  check-server:
    name: Check Server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install --frozen-lockfile
      
      - run: bun check
        working-directory: ./server
      
  check-biome:
    name: Check Biome
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install --frozen-lockfile
      
      - run: bun run check:biome
